// moteur/langues/fr.js
// Textes de l'interface en français (langue par défaut). Pour une nouvelle langue, copier ce fichier
// sous moteur/langues/<code>.js, traduire chaque texte en gardant les mêmes clés, puis déclarer la
// langue dans site.js (langues: ['fr', '<code>']). Les fonctions reçoivent les valeurs à insérer.

export default {
  code: 'fr',
  locale: 'fr-FR',
  ogLocale: 'fr_FR',
  separateurDecimal: ',',
  devise: 'EUR',
  // Segments d'adresse des pages fixes (traduisibles ; le préfixe /<code>/ s'ajoute hors langue par défaut).
  chemins: { devis: 'devis', corpsDeMetier: 'corps-de-metier', mentionsLegales: 'mentions-legales', confidentialite: 'confidentialite', widget: 'widget' },

  page: {
    evitement: "Aller au contenu",
    miseAJour: "Mise à jour",
    recharger: "Recharger",
    plusTard: "Plus tard",
    navigationPrincipale: "Principal",
    monDevis: "Mon devis",
    monDevisCourt: "Devis",
    informationsLegales: "Informations légales",
    mentionsLegales: "Mentions légales",
    confidentialite: "Confidentialité",
    gererCookies: "Gérer mes choix de cookies",
    menuCorps: "Corps de métier",
    tousLesCalculateurs: "Tous les calculateurs",
    filAriane: "Fil d’Ariane",
    accueil: "Accueil",
    tousLesCorps: "Tous les corps de métier",
    nouvelleVersion: (nom) => `Nouvelle version de ${nom} disponible.`,
  },
  navigation: {
    bouton: "Calculateurs",
    panneau: "Tous les calculateurs",
    recherche: "Rechercher un calculateur",
    exemple: "carrelage, béton, peinture…",
    parType: "Par type de chantier",
    parCorps: "Par corps de métier",
    aucun: "Aucun calculateur ne correspond à cette recherche.",
    trouves: (nombre) => (nombre > 1 ? `${nombre} calculateurs trouvés.` : '1 calculateur trouvé.'),
  },
  commun: {
    piece: "Pièce",
    action: "Action",
    nom: "Nom",
    lienPartenaire: "Lien partenaire",
    publicite: "Publicité",
    apercuContenu: "<span class=\"pub-apercu pub-apercu-contenu\">Emplacement publicitaire<br><span class=\"pub-format\"></span></span>",
    corpsDeMetier: "Corps de métier",
    aCompleter: "À compléter",
    apercuLateral: (largeur, hauteur) => `Emplacement publicitaire<br>${largeur} × ${hauteur}`,
  },
  theme: {
    modeNuit: "Mode nuit",
    modeJour: "Mode jour",
    modeNuit: "Mode nuit",
    versClair: "Passer à l’affichage clair",
    versSombre: "Passer à l’affichage sombre",
  },
  appli: {
    installerTexte: "Une icône sur l’écran d’accueil ouvre directement le site, en plein écran, et les calculateurs fonctionnent même sans réseau sur le chantier.",
    installerBouton: "Installer l’application",
    raccourciRecapitulatif: "Mon récapitulatif",
    raccourciCourt: "Récapitulatif",
    installerTitre: (nom) => `Installer ${nom} sur votre téléphone`,
    installerIphone: "Sur iPhone ou iPad, dans Safari : touchez le bouton <strong>Partager</strong>, puis <strong>Sur l’écran d’accueil</strong>.",
    installerAutre: "Dans le menu du navigateur, choisissez <strong>Installer l’application</strong> ou <strong>Ajouter à l’écran d’accueil</strong>.",
  },
  unites: {
    interrupteur: "ft/lb : afficher les équivalents impériaux",
    interrupteurTitre: "Afficher les équivalents impériaux (pieds, livres, gallons)",
    titre: "Unités de mesure",
    case: "Afficher les équivalents impériaux (pieds, livres, gallons)",
    gallon: "Gallon",
    gallonUk: "Britannique (4,55 L)",
    gallonUs: "Américain (3,79 L)",
    explication: "Les calculs et les produits restent en unités métriques, vendus en France : l’équivalent s’affiche entre parenthèses.",
  },
  formulaire: {
    facultatif: "facultatif",
    calculeOuvertures: "Calculé d’après les ouvertures placées sur le plan.",
    vosDonnees: "Vos données",
    reglagesAvances: "Réglages avancés",
    reglagesAvancesIntro: "Valeurs courantes déjà renseignées : modifiez-les seulement si votre produit ou votre chantier est différent.",
    prix: "Prix pour le récapitulatif (facultatif)",
    prixIntro: "Renseignez vos prix pour obtenir un total chiffré dans le récapitulatif.",
    reinitialiser: "Revenir aux valeurs de départ",
    saisirNombre: "Saisissez un nombre, par exemple 1 250,50.",
    schema: (libelle) => `Schéma : ${libelle}`,
    minimum: (valeur) => `La valeur doit être au moins égale à ${valeur}.`,
    maximum: (valeur) => `La valeur doit être au plus égale à ${valeur}.`,
  },
  aideChoix: {
    titre: "Aidez-moi à choisir",
    intro: "Répondez aux questions : les champs concernés se remplissent, et restent modifiables.",
    oui: "oui",
    non: "non",
    recommandation: (raisons) => `Recommandation. ${raisons.join(' ; ')}.`,
  },
  plan: {
    titre: "Forme de la pièce",
    consigne: "Faites glisser les angles pour ajuster la forme de la pièce.",
    aideTitre: "Comment dessiner une forme atypique ?",
    aideTexte: "Touchez un rond blanc au milieu d’un côté pour y ajouter un angle. Pour partir de zéro, choisissez « Dessiner librement », placez les angles un par un sur le plan, puis touchez l’angle A pour fermer la forme. Le tableau « Ajuster les angles au centimètre près » permet aussi de saisir chaque angle.",
    largeur: "Largeur (cm)",
    longueur: "Longueur (cm)",
    rectangle: "Créer un rectangle",
    pieceEnL: "Partir d’une pièce en L",
    libre: "Dessiner librement",
    coordonnees: "Ajuster les angles au centimètre près",
    coordonneesLegende: "Position de chaque angle en centimètres, mesurée depuis le coin haut gauche du plan",
    colAngle: "Angle",
    colHorizontal: "Horizontal",
    colVertical: "Vertical",
    colCote: "Côté suivant",
    ajouterAngle: "Ajouter un angle",
    formeOuverte: "Placez au moins trois angles sur le plan, puis cliquez sur l’angle A pour fermer la forme.",
    formeCroisee: "Deux côtés se croisent ou deux angles se superposent : déplacez un angle pour corriger la forme.",
    rectangleManquant: "Indiquez une largeur et une longueur en centimètres pour créer le rectangle.",
    ajouterAngleEntre: (a, b) => `Ajouter un angle entre ${a} et ${b}`,
    angleDessin: (angle) => `Angle ${angle} : faire glisser pour le déplacer`,
    anglePosition: (angle, axe) => `Angle ${angle}, position ${axe === 0 ? 'horizontale' : 'verticale'} en centimètres`,
    supprimerAngle: (angle) => `Supprimer l’angle ${angle}`,
    cote: (a, b, longueur) => `${a} à ${b} : ${longueur}`,
    resumeOuvertures: (description, surface) => ` Ouvertures : ${description}, soit ${surface} m².`,
    resume: (surface, perimetre) => `Surface au sol : ${surface} m². Périmètre : ${perimetre} m.`,
  },
  pieces: {
    region: "Pièces du chantier",
    nom: "Nom de la pièce",
    hauteur: "Hauteur sous plafond (m)",
    nouvelle: "Nouvelle pièce",
    dupliquer: "Dupliquer",
    supprimer: "Supprimer",
    aide: "Chaque pièce garde son plan, ses ouvertures et sa hauteur, d’un calculateur à l’autre. Les lignes ajoutées au devis portent le nom de la pièce.",
    nomParDefaut: "Pièce",
    premiere: "Pièce 1",
    confirmerSuppression: (nom) => `Supprimer la pièce « ${nom} » et son plan ?`,
    copie: (nom) => `${nom} (copie)`,
  },
  natures: {
    piece: {
      titre: "Forme de la pièce", base: "Pièce", objet: "Pièce", nom: "Nom de la pièce", nouvelle: "Nouvelle pièce",
      aide: "Chaque pièce garde son plan, ses ouvertures et sa hauteur, d’un calculateur à l’autre. Les lignes ajoutées au devis portent le nom de la pièce.",
      ceci: "Cette pièce", tous: "Tout le chantier",
      largeur: "Largeur (cm)", longueur: "Longueur (cm)", largeurDefaut: 400, longueurDefaut: 300, rectangle: "Créer un rectangle",
      elementsTitre: "Éléments à déduire",
      consigneElements: "Trémie d’escalier, gaine technique, conduit de cheminée : leur surface est retirée de celle de la pièce. Position du coin de départ en centimètres, depuis l’angle A. Dimensions courantes proposées, à vérifier sur place.",
    },
    zone: {
      resume: (surface, longueur, largeur, nombre, deduite) => `Surface de la zone : ${surface} m²${nombre ? ` (${nombre} élément${nombre > 1 ? 's' : ''} déduit${nombre > 1 ? 's' : ''}, ${deduite} m²)` : ''}. Dimensions hors tout : ${longueur} × ${largeur} m.`,
      titre: "Forme de la zone", base: "Zone", objet: "Zone", nom: "Nom de la zone", nouvelle: "Nouvelle zone",
      aide: "Dalle, terrasse, allée : chaque zone garde sa forme d’un calculateur à l’autre et apparaît dans le plan d’ensemble, à côté des pièces.",
      ceci: "Cette zone", tous: "Toutes les zones",
      largeur: "Longueur (cm)", longueur: "Largeur (cm)", largeurDefaut: 500, longueurDefaut: 400, rectangle: "Créer un rectangle",
      elementsTitre: "Éléments à déduire",
      consigneElements: "Regard, massif existant : leur surface est retirée de la zone. Position du coin de départ en centimètres, depuis l’angle A.",
    },
    mur: {
      resume: (surface, longueur, hauteur, nombre, deduite) => `Surface du mur : ${surface} m²${nombre ? `, ${nombre} ouverture${nombre > 1 ? 's' : ''} déduite${nombre > 1 ? 's' : ''} (${deduite} m²)` : ''}. Longueur : ${longueur} m, hauteur hors tout : ${hauteur} m.`,
      titre: "Mur vu de face", base: "Mur", objet: "Mur", nom: "Nom du mur", nouvelle: "Nouveau mur",
      aide: "Le mur est dessiné de face : la largeur du dessin est sa longueur, sa hauteur est celle du mur. Pour une façade à pignon, partez du modèle « Mur avec pignon ».",
      ceci: "Ce mur", tous: "Tous les murs",
      largeur: "Longueur du mur (cm)", longueur: "Hauteur sous l’égout (cm)", largeurDefaut: 500, longueurDefaut: 250, rectangle: "Mur rectangulaire",
      elementsTitre: "Portes et fenêtres",
      consigneElements: "Chaque ouverture est un rectangle posé sur la face : position de son coin haut gauche en centimètres, depuis le coin haut gauche du dessin. Sa surface est déduite du mur.",
    },
    pan: {
      resume: (surface, longueur, profondeur, nombre, deduite) => `Surface du pan vue du dessus : ${surface} m²${nombre ? ` (${nombre} élément${nombre > 1 ? 's' : ''} déduit${nombre > 1 ? 's' : ''}, ${deduite} m²)` : ''}. Longueur hors tout : ${longueur} m, profondeur : ${profondeur} m. La pente donne la surface réelle.`,
      titre: "Pan de toit, vu du dessus", base: "Pan", objet: "Pan", nom: "Nom du pan", nouvelle: "Nouveau pan",
      aide: "Dessinez le pan vu du dessus, en projection au sol : la pente, saisie dans le calculateur, donne la surface réelle de couverture.",
      ceci: "Ce pan", tous: "Tous les pans",
      largeur: "Longueur à l’égout (cm)", longueur: "Profondeur vue du dessus (cm)", largeurDefaut: 1000, longueurDefaut: 450, rectangle: "Pan rectangulaire",
      elementsTitre: "Éléments à déduire",
      consigneElements: "Fenêtre de toit, souche de cheminée : leur surface est retirée de la couverture. Position du coin de départ en centimètres, depuis l’angle A.",
    },
  },
  modeles: { l: "Partir d’une pièce en L", libre: "Dessiner librement", pignon: "Mur avec pignon", trapeze: "Pan en trapèze (croupe)", triangle: "Pan triangulaire" },
  modeDimensions: { titre: "Dimensions", saisie: "Saisir les dimensions", dessin: "Dessiner sur un plan" },
  depuisPlan: {
    titre: "Partir des murs du plan",
    libelle: "Mur d’une pièce ou façades",
    creer: "Créer ce mur",
    facade: (nombre) => `Toutes les façades du plan d’ensemble : une face par mur extérieur (${nombre})`,
    creees: (nombre) => `${nombre} façades créées à partir du plan, une par mur extérieur : choisissez « Tous les murs » pour les additionner.`,
    murPiece: (piece, a, b, longueur) => `${piece}, mur ${a} → ${b} (${longueur} m)`,
    aucun: "Aucun plan de pièce enregistré : dessinez d’abord les pièces, par exemple dans le calculateur de peinture.",
    cree: (nom) => `« ${nom} » créé à partir du plan : ajustez sa hauteur et ses ouvertures si besoin.`,
    nomMur: (piece, a, b) => `${piece}, mur ${a} → ${b}`,
  },
  portee: {
    titre: "Calculer pour",
    piece: "Cette pièce",
    niveau: "Tout le niveau",
    chantier: "Tout le chantier",
    detail: "Détail par pièce",
    variable: "selon la pièce",
    ajoutees: (lignes, pieces) => `${lignes} ligne${lignes > 1 ? 's' : ''} ajoutée${lignes > 1 ? 's' : ''} au devis pour ${pieces} pièce${pieces > 1 ? 's' : ''}.`,
    exclue: (nom, message) => `${nom} n’est pas comptée : ${message}`,
  },
  niveaux: {
    niveauPiece: "Niveau",
    affiche: "Niveau affiché",
    nom: "Nom du niveau",
    ajouter: "Nouveau niveau",
    nouveau: (rang) => `Étage ${rang}`,
    vide: "Aucune pièce sur ce niveau : ajoutez-en une avec « Nouvelle pièce ».",
  },
  elements: {
    titre: "Éléments à déduire",
    consigne: "Trémie d’escalier, gaine technique, conduit de cheminée : leur surface est retirée de celle de la pièce. Position du coin de départ en centimètres, depuis l’angle A. Dimensions courantes proposées, à vérifier sur place.",
    typeLibelle: "Élément",
    ajouter: "Ajouter l’élément",
    types: { tremie: "Trémie d’escalier", gaine: "Gaine technique", conduit: "Conduit de cheminée", regard: "Regard", porte: "Porte", fenetre: "Fenêtre", fenetreToit: "Fenêtre de toit", cheminee: "Souche de cheminée", autre: "Autre élément" },
    legende: "Éléments à déduire : position et dimensions en centimètres",
    colElement: "Élément",
    colLargeur: "Largeur (cm)",
    colLongueur: "Longueur (cm)",
    etiquetteX: (nom) => `${nom}, position horizontale en centimètres`,
    etiquetteY: (nom) => `${nom}, position verticale en centimètres`,
    etiquetteLargeur: (nom) => `${nom}, largeur en centimètres`,
    etiquetteLongueur: (nom) => `${nom}, longueur en centimètres`,
    supprimer: (nom) => `Supprimer ${nom}`,
  },
  suggestion: {
    reprendre: "Reprendre",
    longueurFacades: (valeur) => `D’après votre plan d’ensemble : ${valeur} m de façades (murs extérieurs).`,
    longueurCloisons: (valeur) => `D’après votre plan d’ensemble : ${valeur} m de cloisons, chacune comptée une fois.`,
    surfaceTableauxExterieurs: (valeur) => `D’après votre plan d’ensemble : ${valeur} m² de retours de tableau sur les murs extérieurs.`,
    repris: "Valeur reprise du plan d’ensemble.",
  },
  ensemble: {
    choixVue: "Vue du plan",
    vuePiece: "Cette pièce",
    vueEnsemble: "Plan d’ensemble",
    consigne: "Touchez une pièce pour la sélectionner : le calcul porte sur elle. Faites-la glisser pour la placer ; près d’une autre pièce, elle se cale à l’épaisseur du mur qui les sépare.",
    tourner: "Tourner la pièce d’un quart de tour",
    modifier: "Modifier la forme de cette pièce",
    clavier: "Placer les pièces au clavier",
    legende: "Position de chaque pièce dans le plan d’ensemble, en centimètres, et rotation",
    colX: "Horizontal (cm)",
    colY: "Vertical (cm)",
    colRotation: "Rotation",
    rotations: ["0°", "90°", "180°", "270°"],
    selectionner: "Sélectionner",
    selectionnee: "Sélectionnée",
    etiquetteX: (nom) => `${nom}, position horizontale en centimètres`,
    etiquetteY: (nom) => `${nom}, position verticale en centimètres`,
    etiquetteRotation: (nom) => `${nom}, rotation`,
    titrePiece: (nom, surface) => `${nom}, ${surface} m² : toucher pour sélectionner, faire glisser pour déplacer`,
    resume: (nombre, surface, active) => `${nombre} pièce${nombre > 1 ? 's' : ''}, surface habitable : ${surface} m². Pièce sélectionnée : ${active}.`,
    chevauchement: (a, b) => ` Attention : ${a} et ${b} se chevauchent ou n’ont pas la place de leur mur.`,
    aimantee: (autre) => ` Calée contre ${autre}.`,
    mesures: (emprise, facades) => ` Emprise au sol, murs compris : ${emprise} m². Façades : ${facades} m.`,
  },
  murs: {
    titre: "Murs et épaisseurs",
    consigne: "La pièce est dessinée à ses cotes intérieures ; chaque mur s’ajoute vers l’extérieur. Épaisseurs proposées : mur extérieur 30 cm (maçonnerie et doublage isolé), mur porteur 20 cm, cloison 7 cm, à vérifier selon votre bâtiment.",
    types: { exterieur: "Mur extérieur", porteur: "Mur porteur intérieur", cloison: "Cloison" },
    tousLibelle: "Tous les murs :",
    appliquer: "Appliquer à tous les murs",
    legende: "Murs de la pièce : longueur intérieure, type et épaisseur en centimètres",
    colMur: "Mur",
    colLongueur: "Longueur",
    colType: "Type",
    colEpaisseur: "Épaisseur (cm)",
    etiquetteType: (mur) => `Mur ${mur}, type`,
    etiquetteEpaisseur: (mur) => `Mur ${mur}, épaisseur en centimètres`,
    resume: (surface) => ` Hors tout, murs compris : ${surface} m².`,
  },
  ouvertures: {
    partagee: "Ouverture de la pièce voisine, sur le mur commun : elle se modifie depuis cette pièce-là",
    titre: "Portes et fenêtres",
    consigne: "Ajoutez les ouvertures, puis faites-les glisser le long du mur sur le plan, ou ajustez-les dans le tableau. Dimensions proposées : porte 83 × 204 cm, fenêtre 120 × 135 cm, porte-fenêtre 120 × 215 cm, à vérifier sur place.",
    ajouterPorte: "Ajouter une porte",
    ajouterFenetre: "Ajouter une fenêtre",
    ajouterPorteFenetre: "Ajouter une porte-fenêtre",
    legende: "Ouvertures : type, mur, dimensions en centimètres et distance depuis l’angle de départ du mur",
    colType: "Type",
    colMur: "Mur",
    colLargeur: "Largeur",
    colHauteur: "Hauteur",
    colPosition: "Depuis l’angle",
    etiquetteType: "type",
    etiquetteMur: "mur",
    etiquetteLargeur: "largeur en centimètres",
    etiquetteHauteur: "hauteur en centimètres",
    etiquettePosition: "distance depuis l’angle de départ en centimètres",
    formeOuverte: "Fermez d’abord la forme de la pièce pour y placer des ouvertures.",
    titreDessin: (nom, type, largeur, hauteur) => `${nom}, ${type} de ${largeur} × ${hauteur} cm : faire glisser le long du mur`,
    supprimer: (nom) => `Supprimer ${nom}`,
    porte: ['porte', 'portes'],
    fenetre: ['fenêtre', 'fenêtres'],
    porteFenetre: ['porte-fenêtre', 'portes-fenêtres'],
    types: { porte: 'Porte', fenetre: 'Fenêtre', 'porte-fenetre': 'Porte-fenêtre' },
    abreviations: { porte: 'P', fenetre: 'F', 'porte-fenetre': 'PF' },
  },
  resultat: {
    titre: "Résultat",
    attentePlan: "Complétez la forme de la pièce et les champs obligatoires pour afficher le résultat.",
    attente: "Remplissez les champs obligatoires pour afficher le résultat.",
    voirDetail: "Voir le détail",
  },
  calculateur: {
    aSavoir: "À savoir avant de commencer :",
    javascript: "Ce calculateur a besoin de JavaScript pour fonctionner.",
    explication: "Comment le calcul est fait",
    faq: "Questions fréquentes",
    lies: "Calculateurs liés",
    surtitre: (rubrique) => `Calculateur · ${rubrique}`,
    verifieLe: "Valeurs v\u00e9rifi\u00e9es le ",
    tousDuCorps: (nom) => `Tous les calculateurs du corps de métier « ${nom} »`,
  },
  guide: {
    erreurs: "Erreurs fréquentes",
    conseils: "Conseils de mise en œuvre",
    normes: "Normes de référence",
  },
  devis: {
    voir: "Voir mon devis",
    titre: "Récapitulatif des besoins",
    chapo: "Les quantités ajoutées depuis les calculateurs s’additionnent ici, classées par corps de métier. Remplacez les prix par ceux de votre fournisseur, puis téléchargez le récapitulatif en PDF. Rien n’est envoyé : tout reste dans votre navigateur.",
    partageTitre: "Récapitulatif partagé",
    importOuvrir: "Ouvrir ce récapitulatif",
    importAjouter: "L’ajouter à mon devis",
    importIgnorer: "Ignorer",
    designation: "Désignation",
    quantite: "Quantité",
    unite: "Unité",
    voirCalculateurs: "Voir les calculateurs",
    materiaux: "Matériaux",
    regrouperPar: "Regrouper par",
    tableau: "Tableau des matériaux, défilable horizontalement",
    prixUnitaire: "Prix unitaire (€)",
    total: "Total",
    tvaCase: "Mes prix sont hors taxes : calculer la TVA",
    tvaTaux: "Taux de TVA",
    tvaAide: "Les taux de 10 % et 5,5 % s’appliquent sous conditions aux travaux facturés par une entreprise. Les matériaux achetés directement par un particulier sont soumis à 20 %.",
    pdf: "Télécharger le récapitulatif (PDF)",
    email: "Envoyer par e-mail",
    partager: "Partager…",
    copierLien: "Copier le lien de partage",
    csv: "Exporter pour un tableur (CSV)",
    imprimer: "Imprimer",
    vider: "Vider le récapitulatif",
    lienPartage: "Lien de partage du récapitulatif",
    description: "Récapitulatif des matériaux d’un chantier, cumulé à partir des calculateurs.",
    aucunResultat: "Complétez d’abord le calcul : aucun résultat à ajouter.",
    aucuneQuantite: "Aucune quantité à ajouter pour ce calcul.",
    sansPiece: "Sans pièce",
    divers: "Divers",
    prixEtiquette: "Prix unitaire en euros",
    retirer: "Retirer",
    totalHt: "Total hors taxes",
    totalTtc: "Total TTC",
    enteteCsv: "Désignation;Pièce;Détail;Lot;Quantité;Unité;Prix unitaire;Total",
    confirmerVider: "Retirer toutes les lignes du devis ?",
    zone: "Pièce ou zone <small>facultatif, reprise dans le devis</small>",
    complements: "Ajouter aussi les produits d’accompagnement : ",
    ajouter: "Ajouter au devis",
    vide: "Votre récapitulatif est vide. Ajoutez des quantités depuis un calculateur.",
    lignesAjoutees: (nombre) => (nombre > 1 ? `${nombre} lignes ajoutées au devis.` : '1 ligne ajoutée au devis.'),
    retirerEtiquette: (designation) => `Retirer ${designation} du devis`,
    tvaA: (taux) => `TVA à ${taux} %`,
  },
  article: {
    titre: "Ajouter un article sans calculateur",
    aide: "Porte, WC, radiateur, appareillage : tout ce qui se compte à la pièce.",
    uniteParDefaut: "pièce",
    ajouter: "Ajouter au récapitulatif",
    designationManquante: "Indiquez la désignation de l’article.",
    quantiteManquante: "Indiquez une quantité supérieure à zéro.",
    origine: "Article ajouté à la main",
    prix: "Prix unitaire (€) <small class=\"facultatif\">facultatif</small>",
    ajoute: (designation) => `« ${designation} » ajouté au récapitulatif.`,
  },
  chantier: {
    titre: "Informations du chantier",
    aide: "Facultatif : ce que vous renseignez ici apparaît en tête du PDF. Laissez vide ce que vous ne souhaitez pas faire figurer, comme l’adresse.",
    nom: "Nom du chantier ou du client",
    adresse: "Adresse du chantier",
    etabliPar: "Établi par",
  },
  email: {
    pdfJoint: "\\n\\nLe récapitulatif complet est dans le PDF joint à ce message.",
    tropLong: "Le récapitulatif est trop long pour tenir dans le lien d’un e-mail : le PDF vient d’être téléchargé, joignez-le au message qui s’ouvre.",
    ouverture: "Votre messagerie s’ouvre avec le récapitulatif et son lien.",
    adresse: "Adresse : ",
    etabliPar: "\u00c9tabli par : ",
    totalHt: "Total HT : ",
    tva: (taux, montant) => `TVA ${taux} % : ${montant}`,
    totalTtc: "Total TTC : ",
    etabliAvec: (nom) => `Établi avec ${nom}`,
    ouvrir: "Pour ouvrir ce r\u00e9capitulatif et le modifier :",
  },
  partage: {
    partagePdf: "Récapitulatif partagé en PDF.",
    partage: "Récapitulatif partagé.",
    echec: "Le partage n’a pas abouti : téléchargez le PDF ou copiez le lien.",
    lienCopie: "Lien copié : collez-le dans un message ou un courriel.",
    copierManuel: "Copiez le lien affiché ci-dessous.",
    pdfJoint: (sujet) => `${sujet} (PDF joint)`,
    importTexte: (nombre, nom) => `Ce lien contient un récapitulatif de ${nombre} ligne${nombre > 1 ? 's' : ''}${nom ? ` pour « ${nom} »` : ''}.`,
  },
  achat: {
    acheter: "Acheter",
    acheterPdf: "Acheter (lien partenaire)",
    acheterEtiquette: (designation) => `Acheter : ${designation} (lien partenaire, nouvel onglet)`,
  },
  pdf: {
    titre: "Récapitulatif des besoins du chantier",
    ouvrirEnLigne: "Ouvrir et modifier ce récapitulatif en ligne",
    etabliLe: (date) => `Établi le ${date}`,
    avertissement: "Quantités estimées à titre indicatif. Aucun dimensionnement d’ouvrage : vérifiez les règles de pose et les fiches des fabricants.",
    mention: (nom, adresse) => `Quantités calculées avec ${nom}, calculateurs gratuits pour le bâtiment : ${adresse}`,
  },
  integration: {
    titre: "Intégrer ce calculateur sur votre site",
    texte: "Copiez ce code dans une page de votre site : le calculateur s’y affiche, ajuste sa hauteur tout seul, et un lien renvoie vers cette page.",
    theme: "Thème du calculateur intégré",
    clair: "Clair",
    sombre: "Sombre",
    code: "Code à copier",
    copier: "Copier le code",
    credit: (nom) => `, un calculateur ${nom}`,
    source: (titre, nom) => `${titre} sur ${nom}`,
    copie: "Code copié.",
    copieManuelle: "Le code est sélectionné : copiez-le avec Ctrl + C (ou Cmd + C).",
  },
  mentions: {
    editeur: "Éditeur du site",
    statut: "Statut",
    adresse: "Adresse",
    contact: "Contact",
    directeur: "Directeur de la publication",
    hebergeur: "Hébergeur",
    hebergement: "Hébergement",
    limites: "Limites des résultats",
    limitesTexte: "Les calculateurs de ce site fournissent des estimations à titre indicatif. Ils ne remplacent pas l’avis d’un professionnel (notaire, expert-comptable, conseiller financier).",
    description: (nom) => `Mentions légales du site ${nom}.`,
  },
  confidentialite: {
    titre: "Politique de confidentialité",
    donneesTitre: "Vos calculs restent sur votre appareil",
    publiciteTitre: "Publicité et cookies",
    droitsTitre: "Vos droits",
    description: (nom) => `Politique de confidentialité et gestion des cookies du site ${nom}.`,
    donnees: (nom, avecDevis) => `<p>Les calculateurs fonctionnent entièrement dans votre navigateur. Les valeurs saisies, la forme des pièces dessinées${avecDevis ? ', le récapitulatif et les informations de chantier' : ''} et le choix du mode d’affichage sont enregistrés uniquement dans votre navigateur (stockage local). Ils ne sont jamais envoyés à ${nom} ni à un tiers.</p>
        <p>Vous pouvez les effacer à tout moment en vidant les données du site dans les réglages de votre navigateur.</p>
        ${avecDevis ? '<p>Un lien de partage de récapitulatif contient les données du récapitulatif dans l’adresse elle-même, après le signe #. Cette partie de l’adresse n’est pas transmise au serveur : seules les personnes à qui vous envoyez le lien y ont accès.</p>' : ''}`,
    publicite: (avecRegie) => `${avecRegie ? `<p>Le site est financé par la publicité, diffusée par Google AdSense. Google et ses partenaires peuvent utiliser des cookies ou d’autres traceurs pour afficher des annonces, les mesurer et, si vous l’acceptez, les personnaliser.</p>
        <p>Ces traceurs ne sont déposés qu’après votre choix, exprimé dans la fenêtre de consentement affichée lors de votre première visite. Vous pouvez accepter, refuser ou choisir finalité par finalité, et modifier votre choix à tout moment avec le lien « Gérer mes choix de cookies » en bas de chaque page. Refuser n’empêche pas d’utiliser le site.</p>
        <p>Pour en savoir plus sur l’utilisation des données par Google : <a href="https://policies.google.com/technologies/partner-sites?hl=fr">Comment Google utilise les données des sites partenaires</a>.</p>` : '<p>Le site ne dépose aucun cookie publicitaire ni de mesure d’audience.</p>'}`,
    droits: (contact) => `<p>Vous disposez d’un droit d’accès, de rectification, d’effacement et d’opposition sur les données vous concernant. Pour l’exercer, écrivez à : ${contact}. Vous pouvez aussi adresser une réclamation à la CNIL (<a href="https://www.cnil.fr">cnil.fr</a>).</p>`,
  },
  introuvable: {
    titre: "Cette page n’existe pas",
    texte: "L’adresse est peut-être mal saisie, ou le calculateur a été déplacé.",
    lien: "Voir tous les calculateurs",
    description: "Page introuvable.",
    titreCourt: "Page introuvable",
  },
};
